_metadata_:
  version: '1.0'
  output_tag: ==ci==
  save_figs: true
  description: Full profile for CI 
#
# ------ LinearReg -------------------------------------------------
#
LINR1:
  notebook_id: LINR1
  notebook_dir: LinearReg
  notebook_src: 01-Linear-Regression.ipynb
  notebook_tag: default
GRAD1:
  notebook_id: GRAD1
  notebook_dir: LinearReg
  notebook_src: 02-Gradient-descent.ipynb
  notebook_tag: default
POLR1:
  notebook_id: POLR1
  notebook_dir: LinearReg
  notebook_src: 03-Polynomial-Regression.ipynb
  notebook_tag: default
LOGR1:
  notebook_id: LOGR1
  notebook_dir: LinearReg
  notebook_src: 04-Logistic-Regression.ipynb
  notebook_tag: default
PER57:
  notebook_id: PER57
  notebook_dir: IRIS
  notebook_src: 01-Simple-Perceptron.ipynb
  notebook_tag: default
#
# ------ BHPD ------------------------------------------------------
#
BHPD1:
  notebook_id: BHPD1
  notebook_dir: BHPD
  notebook_src: 01-DNN-Regression.ipynb
  notebook_tag: default
BHPD2:
  notebook_id: BHPD2
  notebook_dir: BHPD
  notebook_src: 02-DNN-Regression-Premium.ipynb
  notebook_tag: default
#
# ------ MNIST -----------------------------------------------------
#
MNIST1:
  notebook_id: MNIST1
  notebook_dir: MNIST
  notebook_src: 01-DNN-MNIST.ipynb
  notebook_tag: default
#
# ------ GTSRB -----------------------------------------------------
#
GTSRB1:
  notebook_id: GTSRB1
  notebook_dir: GTSRB
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_tag: default
  overrides:
    scale: 0.01
    output_dir: './data'
GTSRB2:
  notebook_id: GTSRB2
  notebook_dir: GTSRB
  notebook_src: 02-First-convolutions.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB2_ci
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
GTSRB3:
  notebook_id: GTSRB3
  notebook_dir: GTSRB
  notebook_src: 03-Tracking-and-visualizing.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB3_ci
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
GTSRB4:
  notebook_id: GTSRB4
  notebook_dir: GTSRB
  notebook_src: 04-Data-augmentation.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB4_ci
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
GTSRB5_r1:
  notebook_id: GTSRB5
  notebook_dir: GTSRB
  notebook_src: 05-Full-convolutions.ipynb
  notebook_tag: =1==ci==
  overrides:
    run_dir: ./run/GTSRB5_ci
    enhanced_dir: './data'
    datasets: "['set-24x24-L', 'set-24x24-RGB', 'set-48x48-L', 'set-48x48-RGB', 'set-24x24-L-LHE', 'set-24x24-RGB-HE', 'set-48x48-L-LHE', 'set-48x48-RGB-HE']"
    models: "{'v1':'get_model_v1', 'v2':'get_model_v2', 'v3':'get_model_v3'}"
    batch_size: 64
    epochs: 16
    scale: 1
    with_datagen: False
    verbose: 0
GTSRB5_r2:
  notebook_id: GTSRB5
  notebook_dir: GTSRB
  notebook_src: 05-Full-convolutions.ipynb
  notebook_tag: =2==ci==
  overrides:
    run_dir: ./run/GTSRB5_ci
    enhanced_dir: './data'
    datasets: "['set-48x48-L', 'set-48x48-RGB']"
    models: "{'v2':'get_model_v2', 'v3':'get_model_v3'}"
    batch_size: 64
    epochs: 16
    scale: 1
    with_datagen: False
    verbose: 0
GTSRB6:
  notebook_id: GTSRB6
  notebook_dir: GTSRB
  notebook_src: 06-Notebook-as-a-batch.ipynb
  notebook_tag: default
GTSRB7:
  notebook_id: GTSRB7
  notebook_dir: GTSRB
  notebook_src: 07-Show-report.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB7_ci
    report_dir: ./run/GTSRB5_ci
#
# ------ IMDB ------------------------------------------------------
#
IMDB1:
  notebook_id: IMDB1
  notebook_dir: IMDB
  notebook_src: 01-Embedding-Keras.ipynb
  notebook_tag: default
IMDB2:
  notebook_id: IMDB1
  notebook_dir: IMDB
  notebook_src: 02-Prediction.ipynb
  notebook_tag: default
IMDB3:
  notebook_id: IMDB1
  notebook_dir: IMDB
  notebook_src: 03-LSTM-Keras.ipynb
  notebook_tag: default
#
# ------ SYNOP -----------------------------------------------------
#
SYNOP1:
  notebook_id: SYNOP1
  notebook_dir: SYNOP
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_tag: default
SYNOP2:
  notebook_id: SYNOP2
  notebook_dir: SYNOP
  notebook_src: 02-First-predictions.ipynb
  notebook_tag: default
  overrides:
    scale: 0.5
    train_prop: 0.8
    sequence_len: 16
    batch_size: 32
    epochs: 10
SYNOP3:
  notebook_id: SYNOP3
  notebook_dir: SYNOP
  notebook_src: 03-12h-predictions.ipynb
  notebook_tag: default
  overrides:
    iterations: 4
    scale: 1
    train_prop: 0.8
    sequence_len: 16
    batch_size: 32
    epochs: 10
#
# ------ AE --------------------------------------------------------
#
AE1:
  notebook_id: AE1
  notebook_dir: AE
  notebook_src: 01-AE-with-MNIST.ipynb
  notebook_tag: default
AE2:
  notebook_id: AE2
  notebook_dir: AE
  notebook_src: 02-AE-with-MNIST-post.ipynb
  notebook_tag: default
#
# ------ VAE -------------------------------------------------------
#
VAE1:
  notebook_id: VAE1
  notebook_dir: VAE
  notebook_src: 01-VAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE1_ci
    scale: 1
    latent_dim: 2
    r_loss_factor: 0.994
    batch_size: 64
    epochs: 10
VAE2:
  notebook_id: VAE2
  notebook_dir: VAE
  notebook_src: 02-VAE-with-MNIST-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE1_ci
VAE5:
  notebook_id: VAE5
  notebook_dir: VAE
  notebook_src: 05-About-CelebA.ipynb
  notebook_tag: default
VAE6:
  notebook_id: VAE6
  notebook_dir: VAE
  notebook_src: 06-Prepare-CelebA-datasets.ipynb
  notebook_tag: default
  overrides:
    scale: 0.02
    image_size: '(192,160)'
    output_dir: ./data
    exit_if_exist: False
VAE7:
  notebook_id: VAE7
  notebook_dir: VAE
  notebook_src: 07-Check-CelebA.ipynb
  notebook_tag: default
  overrides:
    image_size: '(192,160)'
    enhanced_dir: './data'
VAE8:
  notebook_id: VAE8
  notebook_dir: VAE
  notebook_src: 08-VAE-with-CelebA.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE8_ci
    scale: 1
    image_size: '(192,160)'
    enhanced_dir: './data'
    latent_dim: 300
    r_loss_factor: 0.6
    batch_size: 64
    epochs: 15
VAE9:
  notebook_id: VAE9
  notebook_dir: VAE
  notebook_src: 09-VAE-with-CelebA-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE8_ci
    image_size: '(192,160)'
    enhanced_dir: './data'
#
# ------ Misc ------------------------------------------------------
#
ACTF1:
  notebook_id: ACTF1
  notebook_dir: Misc
  notebook_src: Activation-Functions.ipynb
  notebook_tag: default
NP1:
  notebook_id: NP1
  notebook_dir: Misc
  notebook_src: Numpy.ipynb
  notebook_tag: default
TSB1:
  notebook_id: TSB1
  notebook_dir: Misc
  notebook_src: Using-Tensorboard.ipynb
  notebook_tag: default
