_metadata_:
  version: '1.0'
  description: Full run on a small cpu
  output_tag: ==ci==
  output_ipynb: ./fidle/run/ci/ipynb
  output_html:  ./fidle/run/ci/html
  report_json:  ./fidle/run/ci/report.json
  report_error: ./fidle/run/ci/error.txt
  environment_vars:
    FIDLE_SAVE_FIGS: true
    TF_CPP_MIN_LOG_LEVEL: 2
#
# ------ LinearReg -------------------------------------------------
#
Nb_LINR1:
  notebook_id: LINR1
  notebook_dir: LinearReg
  notebook_src: 01-Linear-Regression.ipynb
  notebook_tag: default
Nb_GRAD1:
  notebook_id: GRAD1
  notebook_dir: LinearReg
  notebook_src: 02-Gradient-descent.ipynb
  notebook_tag: default
Nb_POLR1:
  notebook_id: POLR1
  notebook_dir: LinearReg
  notebook_src: 03-Polynomial-Regression.ipynb
  notebook_tag: default
Nb_LOGR1:
  notebook_id: LOGR1
  notebook_dir: LinearReg
  notebook_src: 04-Logistic-Regression.ipynb
  notebook_tag: default
Nb_PER57:
  notebook_id: PER57
  notebook_dir: IRIS
  notebook_src: 01-Simple-Perceptron.ipynb
  notebook_tag: default
#
# ------ BHPD ------------------------------------------------------
#
Nb_BHPD1:
  notebook_id: BHPD1
  notebook_dir: BHPD
  notebook_src: 01-DNN-Regression.ipynb
  notebook_tag: default
  overrides:
    fit_verbosity: 2
Nb_BHPD2:
  notebook_id: BHPD2
  notebook_dir: BHPD
  notebook_src: 02-DNN-Regression-Premium.ipynb
  notebook_tag: default
  overrides:
    fit_verbosity: 2
#
# ------ MNIST -----------------------------------------------------
#
Nb_MNIST1:
  notebook_id: MNIST1
  notebook_dir: MNIST
  notebook_src: 01-DNN-MNIST.ipynb
  notebook_tag: default
  overrides:
    fit_verbosity: 2
Nb_MNIST2:
  notebook_id: MNIST2
  notebook_dir: MNIST
  notebook_src: 02-CNN-MNIST.ipynb
  notebook_tag: default
  overrides:
    fit_verbosity: 2
#
# ------ GTSRB -----------------------------------------------------
#
Nb_GTSRB1:
  notebook_id: GTSRB1
  notebook_dir: GTSRB
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_tag: default
  overrides:
    scale: 0.01
    output_dir: ./data
    progress_verbosity: 2

Nb_GTSRB2:
  notebook_id: GTSRB2
  notebook_dir: GTSRB
  notebook_src: 02-First-convolutions.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB2_done
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
    fit_verbosity: 2

Nb_GTSRB3:
  notebook_id: GTSRB3
  notebook_dir: GTSRB
  notebook_src: 03-Tracking-and-visualizing.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB3_done
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
    fit_verbosity: 2

Nb_GTSRB4:
  notebook_id: GTSRB4
  notebook_dir: GTSRB
  notebook_src: 04-Data-augmentation.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB4_done
    enhanced_dir: './data'
    dataset_name: set-24x24-L
    batch_size: 64
    epochs: 5
    scale: 1
    fit_verbosity: 2

Nb_GTSRB5_r1:
  notebook_id: GTSRB5
  notebook_dir: GTSRB
  notebook_src: 05-Full-convolutions.ipynb
  notebook_tag: =1==ci==
  overrides:
    run_dir: ./run/GTSRB5_done
    enhanced_dir: './data'
    datasets: "['set-24x24-L', 'set-24x24-RGB']"
    models: "{'v1':'get_model_v1', 'v2':'get_model_v2'}"
    batch_size: 64
    epochs: 5
    scale: 1
    with_datagen: False
    fit_verbosity: 0

Nb_GTSRB6:
  notebook_id: GTSRB6
  notebook_dir: GTSRB
  notebook_src: 06-Notebook-as-a-batch.ipynb
  notebook_tag: default

Nb_GTSRB7:
  notebook_id: GTSRB7
  notebook_dir: GTSRB
  notebook_src: 07-Show-report.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/GTSRB7_done
    report_dir: ./run/GTSRB5_done
#
# ------ IMDB ------------------------------------------------------
#
Nb_IMDB1:
  notebook_id: IMDB1
  notebook_dir: IMDB
  notebook_src: 01-One-hot-encoding.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    vocab_size: default
    hide_most_frequently: default
    batch_size: default
    epochs: default
    fit_verbosity: 2

Nb_IMDB2:
  notebook_id: IMDB2
  notebook_dir: IMDB
  notebook_src: 02-Keras-embedding.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    vocab_size: default
    hide_most_frequently: default
    review_len: default
    dense_vector_size: default
    batch_size: default
    epochs: default
    output_dir: default

Nb_IMDB3:
  notebook_id: IMDB3
  notebook_dir: IMDB
  notebook_src: 03-Prediction.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    vocab_size: default
    review_len: default
    dictionaries_dir: default

Nb_IMDB4:
  notebook_id: IMDB4
  notebook_dir: IMDB
  notebook_src: 04-Show-vectors.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    vocab_size: default
    review_len: default
    dictionaries_dir: default

Nb_IMDB5:
  notebook_id: IMDB5
  notebook_dir: IMDB
  notebook_src: 05-LSTM-Keras.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    vocab_size: default
    hide_most_frequently: default
    review_len: default
    dense_vector_size: default
    batch_size: default
    epochs: default
    fit_verbosity: 2
    scale: .1
#
# ------ SYNOP -----------------------------------------------------
#
Nb_LADYB1:
  notebook_id: LADYB1
  notebook_dir: SYNOP
  notebook_src: LADYB1-Ladybug.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: 0.1
    train_prop: default
    sequence_len: default
    predict_len: default
    batch_size: default
    epochs: default
    fit_verbosity: 2

Nb_SYNOP1:
  notebook_id: SYNOP1
  notebook_dir: SYNOP
  notebook_src: SYNOP1-Preparation-of-data.ipynb
  notebook_tag: default
  overrides:
    output_dir: default

Nb_SYNOP2:
  notebook_id: SYNOP2
  notebook_dir: SYNOP
  notebook_src: SYNOP2-First-predictions.ipynb
  notebook_tag: default
  overrides:
    scale: 0.1
    train_prop: default
    sequence_len: default
    batch_size: default
    epochs: default

Nb_SYNOP3:
  notebook_id: SYNOP3
  notebook_dir: SYNOP
  notebook_src: SYNOP3-12h-predictions.ipynb
  notebook_tag: default
  overrides:
    iterations: default
    scale: default
    train_prop: default
    sequence_len: default
#
# ------ AE --------------------------------------------------------
#
Nb_AE1:
  notebook_id: AE1
  notebook_dir: AE
  notebook_src: 01-Prepare-MNIST-dataset.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: 0.02
    prepared_dataset: default
    progress_verbosity: 2

Nb_AE2:
  notebook_id: AE2
  notebook_dir: AE
  notebook_src: 02-AE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    prepared_dataset: default
    dataset_seed: default
    scale: default
    latent_dim: default
    train_prop: default
    batch_size: default
    epochs: default

Nb_AE3:
  notebook_id: AE3
  notebook_dir: AE
  notebook_src: 03-AE-with-MNIST-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    prepared_dataset: default
    dataset_seed: default
    scale: default
    train_prop: default

Nb_AE4:
  notebook_id: AE4
  notebook_dir: AE
  notebook_src: 04-ExtAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    prepared_dataset: default
    dataset_seed: default
    scale: default
    latent_dim: default
    train_prop: default
    batch_size: default
    epochs: default

Nb_AE5:
  notebook_id: AE5
  notebook_dir: AE
  notebook_src: 05-ExtAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    prepared_dataset: default
    dataset_seed: default
    scale: default
    latent_dim: default
    train_prop: default
    batch_size: default
    epochs: default
#
# ------ VAE -------------------------------------------------------
#
Nb_VAE1:
  notebook_id: VAE1
  notebook_dir: VAE
  notebook_src: 01-VAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    latent_dim: default
    loss_weights: default
    scale: 0.01
    seed: default
    batch_size: default
    epochs: default
    fit_verbosity: 2

Nb_VAE2:
  notebook_id: VAE2
  notebook_dir: VAE
  notebook_src: 02-VAE-with-MNIST.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE2.000
    latent_dim: default
    loss_weights: default
    scale: 0.01
    seed: default
    batch_size: default
    epochs: default
    fit_verbosity: 2

Nb_VAE3:
  notebook_id: VAE3
  notebook_dir: VAE
  notebook_src: 03-VAE-with-MNIST-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: ./run/VAE2.000
    scale: default
    seed: default

Nb_VAE5:
  notebook_id: VAE5
  notebook_dir: VAE
  notebook_src: 05-About-CelebA.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    progress_verbosity: 2
    
Nb_VAE6:
  notebook_id: VAE6
  notebook_dir: VAE
  notebook_src: 06-Prepare-CelebA-datasets.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: 0.01
    seed: default
    cluster_size: default
    image_size: default
    output_dir: ./data
    exit_if_exist: False
    progress_verbosity: 2

Nb_VAE7:
  notebook_id: VAE7
  notebook_dir: VAE
  notebook_src: 07-Check-CelebA.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    image_size: default
    enhanced_dir: ./data
    progress_verbosity: 2

Nb_VAE8:
  notebook_id: VAE8
  notebook_dir: VAE
  notebook_src: 08-VAE-with-CelebA.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    scale: 0.1
    image_size: default
    enhanced_dir: ./data
    latent_dim: default
    loss_weights: default
    batch_size: default
    epochs: default
    progress_verbosity: 2

Nb_VAE9:
  notebook_id: VAE9
  notebook_dir: VAE
  notebook_src: 09-VAE-with-CelebA-post.ipynb
  notebook_tag: default
  overrides:
    run_dir: default
    image_size: default
    enhanced_dir: ./data

# ------ DCGAN -----------------------------------------------------
#
Nb_DCGAN01:
  notebook_id: DCGAN01
  notebook_dir: DCGAN
  notebook_src: 01-DCGAN-Draw-me-a-sheep.ipynb
  notebook_tag: default
  overrides:
    scale: 0.005
    run_dir: default
    latent_dim: default
    epochs: 5
    batch_size: default
    num_img: default
    fit_verbosity: 2
#
# ------ Misc ------------------------------------------------------
#
Nb_ACTF1:
  notebook_id: ACTF1
  notebook_dir: Misc
  notebook_src: Activation-Functions.ipynb
  notebook_tag: default

Nb_NP1:
  notebook_id: NP1
  notebook_dir: Misc
  notebook_src: Numpy.ipynb
  notebook_tag: default
